-- Run through a privileged SQL connection. Entire fixture is rolled back.
begin;
select set_config('test.user',(select id::text from public.profiles limit 1),true);
select set_config('test.category',(select id::text from public.categories order by position limit 1),true);
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.user'),'role','authenticated')::text,true);
insert into public.tasks(id,user_id,date,category_id,title,position) values('aaaaaaaa-0000-0000-0000-000000000001',current_setting('test.user')::uuid,'2020-01-01',current_setting('test.category')::uuid,'[db-test] Past',1024);
set local role authenticated;
do $$ declare r jsonb;t public.tasks; failed boolean;count_rows integer;
begin
  perform public.finalize_my_days();
  if not exists(select 1 from public.day_status where date='2020-01-01' and is_finished) then raise exception 'Offline finalization fallback failed';end if;
  if (select date from public.tasks where id='aaaaaaaa-0000-0000-0000-000000000001')<>'2020-01-01' then raise exception 'Automatic finalization moved tasks';end if;
  if (select count(*) from public.categories)<>7 then raise exception 'Category ownership failed';end if;
  failed:=false;
  begin perform public.planner_mutate('create',jsonb_build_object('date','2020-01-01','category_id',current_setting('test.category'),'title','[db-test] Invalid past')); exception when others then failed:=true;end;
  if not failed then raise exception 'Past insertion allowed';end if;
  update public.tasks set completed=true where id='aaaaaaaa-0000-0000-0000-000000000001';get diagnostics count_rows=row_count;
  if count_rows<>0 then raise exception 'Past update allowed';end if;
  r:=public.planner_mutate('create',jsonb_build_object('date','2040-05-07','category_id',current_setting('test.category'),'title','[db-test] Main'));
  select * into t from public.tasks where id=(r->>'id')::uuid;
  perform public.planner_mutate('toggle',jsonb_build_object('id',t.id,'updated_at',t.updated_at));
  failed:=false;
  begin perform public.planner_mutate('toggle',jsonb_build_object('id',t.id,'updated_at',t.updated_at));exception when others then failed:=true;end;
  if not failed then raise exception 'Stale version accepted';end if;
  select * into t from public.tasks where id=t.id;
  perform public.planner_mutate('copy',jsonb_build_object('id',t.id,'updated_at',t.updated_at,'dates',jsonb_build_array('2040-05-09','2040-05-11')));
  if exists(select 1 from public.tasks where date in('2040-05-09','2040-05-11') and title='[db-test] Main' and completed) then raise exception 'Copy retains completion';end if;
  r:=public.save_day_note('2040-05-07','[db-test] Note',0);
  if (r->>'revision')::integer<>1 then raise exception 'Initial note revision failed';end if;
  r:=public.save_day_note('2040-05-07','Stale note',0);
  if not (r->>'conflict')::boolean then raise exception 'Stale note accepted';end if;
  if (select content from public.day_notes where date='2040-05-07')<>'[db-test] Note' then raise exception 'Conflict overwrote note';end if;
  r:=public.save_day_note('2040-05-07','[db-test] Updated',1);
  if (r->>'revision')::integer<>2 then raise exception 'Note revision did not advance';end if;
  r:=public.save_day_note('2020-01-01','Closed note',0);
  if not (r->>'locked')::boolean then raise exception 'Closed note accepted';end if;
  r:=public.save_study_time('2040-05-07',125,0);
  if not (r->>'locked')::boolean then raise exception 'Future study accepted';end if;
  r:=public.save_study_time('2020-01-01',125,0);
  if not (r->>'locked')::boolean then raise exception 'Past study accepted';end if;
  r:=public.save_study_time('2020-01-01',200,0);
  if not (r->>'locked')::boolean then raise exception 'Past study update accepted';end if;
  r:=public.save_study_time('2020-01-01',135,1);
  if not (r->>'locked')::boolean then raise exception 'Past study update accepted';end if;
  if exists(select 1 from public.day_study_time where date='2020-01-01') then raise exception 'Past write created record';end if;
  failed:=false;
  begin perform public.planner_mutate('finish',jsonb_build_object('date','2040-05-07','mode','leave'));exception when others then failed:=true;end;
  if not failed then raise exception 'Legacy manual closure allowed';end if;
  if exists(select 1 from public.day_status where date='2040-05-07' and is_finished) then raise exception 'Rejected action closed day';end if;
  if has_table_privilege('authenticated','public.day_status','INSERT') or has_table_privilege('authenticated','public.day_notes','UPDATE') or has_table_privilege('authenticated','public.day_study_time','UPDATE') then raise exception 'Direct writes bypass RPC';end if;
  r:=public.planner_mutate('create',jsonb_build_object('date','2040-05-08','category_id',current_setting('test.category'),'title','[db-test] Move'));
  select * into t from public.tasks where id=(r->>'id')::uuid;
  failed:=false;
  begin perform public.planner_mutate('move',jsonb_build_object('id',t.id,'updated_at',t.updated_at,'date','2020-01-01'));exception when others then failed:=true;end;
  if not failed or (select date from public.tasks where id=t.id)<>'2040-05-08' then raise exception 'Move into closed day not atomic';end if;
  r:=public.planner_mutate('create',jsonb_build_object('date','2040-05-10','category_id',current_setting('test.category'),'title','[db-test] Delete'));
  select * into t from public.tasks where id=(r->>'id')::uuid;
  perform public.planner_mutate('delete',jsonb_build_object('id',t.id,'updated_at',t.updated_at));
  perform public.planner_mutate('restore',jsonb_build_object('id',t.id));
  if (select deleted_at from public.tasks where id=t.id) is not null then raise exception 'Undo failed';end if;
end $$;
reset role;
-- Test expired undo with a server-owned timestamp fixture.
update public.tasks set deleted_at=now()-interval '10 seconds' where title='[db-test] Delete';
set local role authenticated;
do $$ declare failed boolean:=false;t uuid;
begin
  select id into t from public.tasks where title='[db-test] Delete';
  begin perform public.planner_mutate('restore',jsonb_build_object('id',t));exception when others then failed:=true;end;
  if not failed then raise exception 'Expired undo accepted';end if;
end $$;
reset role;
-- An unrelated JWT identity cannot see or edit the account's rows.
select set_config('request.jwt.claims','{"sub":"bbbbbbbb-0000-0000-0000-000000000001","role":"authenticated"}',true);
set local role authenticated;
do $$ begin
  if exists(select 1 from public.tasks) or exists(select 1 from public.day_notes) or exists(select 1 from public.day_study_time) or exists(select 1 from public.categories) or exists(select 1 from public.day_status) then raise exception 'Cross-user read leak';end if;
end $$;
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
do $$ declare failed boolean:=false;begin
  begin perform public.finalize_my_days();exception when insufficient_privilege then failed:=true;end;
  if not failed then raise exception 'Anonymous finalizer exposed';end if;
  if has_function_privilege('anon','public.save_day_note(date,text,integer)','EXECUTE') or has_function_privilege('anon','public.save_study_time(date,integer,integer)','EXECUTE') then raise exception 'Anonymous writer exposed';end if;
end $$;
reset role;
rollback;
select 'RLS, immutable history, note conflicts, locked future/past study, rejected manual closure, copy, atomic move, undo and anonymous guards passed' as result;
